sudo: false

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

cache: pip

os:
  - linux

install:
  - pip install .
  - pip install coveralls

script:
  - coverage run tests/run.py

after_success:
  - coveralls

notifications:
  email: false
